### ISSUE TITLE
Fix compatibility with new v1.1 version of Super Mario Bros. 1/3?

### ISSUE THREAD

**Issue by saulfabregwiivc** [Tippek/libretro-fceumm-mod#2]
Hi there

I was testing this modified FCEUmm mod with the romhack made by Corpse Grinder "Super Mario Bros. 1/3" (obviously with the v1.0 version which works fine).

However, lastyear the author updated the custom emulator and also the romhack to v1.1, and when i test it, it loads but it has severely corrupted graphics., making it unplayable.
Could you fix this? Thanks!

PD: I will leave a link to the official SMB 1/3 Discord if you want to check it out :) http://discord.gg/qV7Db9m

**Comment by chunkyjackson** [comment]
> Hi there
> 
> I was testing this modified FCEUmm mod with the romhack made by Corpse Grinder "Super Mario Bros. 1/3" (obviously with the v1.0 version which works fine).
> 
> However, lastyear the author updated the custom emulator and also the romhack to v1.1, and when i test it, it loads but it has severely corrupted graphics., making it unplayable. Could you fix this? Thanks!
> 
> PD: I will leave a link to the official SMB 1/3 Discord if you want to check it out :) http://discord.gg/qV7Db9m

The author of this core is from there  It already has been updated to use v1.1. Also, what platform are you building for? Look through the en-chat in that discord, there are precompiled builds that work for Windows PC, Android, and Switch.

**Comment by saulfabregwiivc** [comment]
> > Hi there
> > I was testing this modified FCEUmm mod with the romhack made by Corpse Grinder "Super Mario Bros. 1/3" (obviously with the v1.0 version which works fine).
> > However, lastyear the author updated the custom emulator and also the romhack to v1.1, and when i test it, it loads but it has severely corrupted graphics., making it unplayable. Could you fix this? Thanks!
> > PD: I will leave a link to the official SMB 1/3 Discord if you want to check it out :) http://discord.gg/qV7Db9m
> 
> The author of this core is from there It already has been updated to use v1.1. Also, what platform are you building for? Look through the en-chat in that discord, there are precompiled builds that work for Windows PC, Android, and Switch.

Thanks for replying.
I'm trying to compile it for Wii, but unfortunately i couldn't.

If anyone can provide me a compiled version or at least the setup used for compiling this for Wii i will be grateful.
Thanks :)

EDIT: Closing this issue, but i need an answer to my question.
